
services:
  - type: web
    name: crypto-futures-bot
    runtime: python
    envVars:
      - key: TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: CHAT_ID
        value: 5919952205
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
