services:
  - type: web
    name: futures-signals-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: TOKEN
      - key: CHAT_ID
